# Generated by Django 5.1.3 on 2024-12-05 08:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sacco', '0002_route_alter_matatu_route'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission'),
        ),
        migrations.AlterUniqueTogether(
            name='revenue',
            unique_together={('matatu', 'date')},
        ),
        migrations.CreateModel(
            name='MatatuRouteRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('matatu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_revenues', to='sacco.matatu')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matatu_revenues', to='sacco.route')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('matatu', 'route', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RouteRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_revenues', to='sacco.route')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('route', 'date')},
            },
        ),
    ]
